name: CD

on:
  push:
    branches: [main]
    # paths:
    #   - '.github/workflows/sample-ping.yml'

env:
  ENABLE_DOWNLOADS_FROM_ARTIFACTORY: false # Optional variable to enable Artifactory downloads
  ALPINE_IMAGE_NAME: my-docker-image
  ALPINE_BUILDER_PATH: ./docker/

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - name: build and push a test image
        run: |
          cat <<EOF>> test.Dockerfile
          FROM ubuntu:20.04
          EOF
          docker build -t test-image:tmp -f test.Dockerfile .
          docker save -o /tmp/testimage.tar test-image:tmp
      - name: Upload image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: testimage
          path: /tmp/testimage.tar

  load-image:
    runs-on: self-hosted
    needs: build-image
    steps:
      - name: Download image from artifact
        uses: actions/download-artifact@v3
        with:
          name: testimage
          path: /tmp
      - name: Load saved image
        run: docker load < /tmp/testimage.tar

  test-run-in-container:
    runs-on: self-hosted
    needs: load-image
    container:
      image: test-image:tmp
    steps:
      - name: test run
        run: echo "Test run successfully!"