name: CD

on:
  push:
    branches: [main]
    # paths:
    #   - '.github/workflows/sample-ping.yml'

env:
  ENABLE_DOWNLOADS_FROM_ARTIFACTORY: false # Optional variable to enable Artifactory downloads
  ALPINE_IMAGE_NAME: my-docker-image
  ALPINE_BUILDER_PATH: ./docker/

jobs:
  check-connectivity:
    runs-on: self-hosted

    steps: 
      - name: Check out repository
        uses: actions/checkout@v3

      # - name: run docker container
      #   run: docker run --name my-docker-container -d my-docker-image "tail -f /dev/null"
      
          
      - name: Install Netcat
        run: |
          echo "Starting Docker container..."
          docker run --rm -v "$(pwd)":/workspace -w /workspace my-docker-image:latest sh -c '
            if command -v apk > /dev/null 2>&1; then
              apk add --no-cache netcat-openbsd
            elif command -v apt-get > /dev/null 2>&1; then
              apt-get update && apt-get install -y netcat
            elif command -v yum > /dev/null 2>&1; then
              yum install -y nc
            else
              echo "Package manager not supported. Unable to install netcat."
              exit 1
            fi
          
            IFS=","
            ALL_SUCCESS=true

            # Loop through each IP in IP_LIST
            for IP in $IP_LIST; do
              echo "Checking connectivity to $IP by ping..."

              if ping -c 5 "$IP"; then
                echo "✅ Connectivity to $IP via ping exists."
              else
                echo "❌ Cannot connect to $IP via ping. Please check network/firewall settings."
                ALL_SUCCESS=false
              fi
            done

            # Check final status
            if [ "$ALL_SUCCESS" = true ]; then
              echo "All IPs are reachable."
            else
              echo "Some IPs failed to respond to ping."
              exit 1
            fi'
