name: ci

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci.yml'

env:
  ALPINE_IMAGE_NAME: my-docker-image
  ALPINE_BUILDER_PATH: ./docker/
  ENABLE_DOWNLOADS_FROM_ARTIFACTORY: false

permissions:
  contents: read

jobs:
  deploy:
    name: ci
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the Docker Alpine Image
        run: |
          echo "Building the Docker image..."
          docker build -t $ALPINE_IMAGE_NAME $ALPINE_BUILDER_PATH 

      - name: check docker images
        run: docker images

      - name: Save Docker image
        run: |
          docker save my-docker-image:latest -o my-docker-image.tar
        # Upload the tarball to make it available to other jobs
      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: my-docker-image
          path: my-docker-image.tar

