# Use the official Python 3.12 Alpine base image
FROM python:3.12-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy any necessary files (if any)
# COPY . .

# Install necessary dependencies (if required)
# RUN pip install -r requirements.txt

# Default command to run Python
CMD ["python"]
