name: Ping IP 

on:
  push:
    branches: [main]

env:
  ENABLE_DOWNLOADS_FROM_ARTIFACTORY: false # Optional variable to enable Artifactory downloads
  IP_LIST: "115.246.57.124,111.118.250.74"

jobs:
  check-connectivity:
    runs-on: self-hosted

    steps: 
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name : check ns-lookup
        run: |
         # nslookup google.com
         ping -c 4 8.8.8.8

      - name: Configure Firewall Rules
        run: |
          whoami
          echo  "check sudoer list"
          sudo -l 
          sudo ufw enable
          # sudo ufw allow OpenSSH
          # sudo ufw allow out to 115.246.57.124 port 22
          # sudo ufw allow out to 111.118.250.74 port 22
          sudo ufw reload
          sudo ufw status
          # sudo ufw show added
          
      # - name: Install Netcat
      #   run: |
      #     if [ -x "$(command -v apk)" ]; then
      #       apk add --no-cache netcat-openbsd
      #     elif [ -x "$(command -v apt-get)" ]; then
      #       sudo apt-get update && sudo apt-get install -y netcat
      #     elif [ -x "$(command -v yum)" ]; then
      #       sudo yum install -y nc
      #     else
      #       echo "Package manager not supported. Unable to install netcat."
      #      exit 1
      #     fi
          
      # - name: Ping IP's
      #   run: |
      #    #  starting to ping the ips
      #     IFS=','; for IP in $IP_LIST; do
      #       echo "Checking connectivity to $IP by ping..."

      #       if ping -c 5 "$IP" ; then
      #         echo "✅ Connectivity to $IP via ping exists."
      #       else
      #         echo "❌ Cannot connect to $IP via ping. Please check network/firewall settings."
      #         ALL_SUCCESS=false
      #       fi
      #     done 

      - name: Check Network Connectivity
        run: |
          
          # Initialize a variable to track failures
          ALL_SUCCESS=true

          # Split the IP_LIST into an array using IFS
          IFS=','; for IP in $IP_LIST; do
            echo "Checking connectivity to $IP on port 22..."

            # Use netcat to check connectivity on port 22 (SSH)
            if nc -z -w 5 "$IP" 22 &>/dev/null; then
              echo "✅ Connectivity to $IP on port 22 exists."
            else
              echo "❌ Cannot connect to $IP on port 22. Please check network/firewall settings."
              ALL_SUCCESS=false
            fi
          done

          # Display final result
          if [ "$ALL_SUCCESS" = true ]; then
            echo "✅ All IPs are reachable on port 22."
          else
            echo "❌ Some IPs are not reachable on port 22. Please check the connectivity."
            exit 1
          fi
